"""empty message

Revision ID: 0bf832bfd8a0
Revises: 
Create Date: 2023-02-06 20:43:21.294044

"""
from alembic import op
import geoalchemy2
import sqlalchemy as sa
import sqlalchemy_utils
from geoalchemy2 import Geometry

# revision identifiers, used by Alembic.
revision = "0bf832bfd8a0"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "course",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("hole_count", sa.Integer(), nullable=True),
        sa.Column(
            "id",
            sqlalchemy_utils.types.uuid.UUIDType(),
            server_default=sa.text(
                "(lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))),2) || '-' || substr('89ab',abs(random()) % 4 + 1, 1) || substr(lower(hex(randomblob(2))),2) || '-' || lower(hex(randomblob(6))))"
            ),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "users",
        sa.Column(
            "active",
            sa.Boolean(),
            server_default=sa.text("(false)"),
            nullable=True,
        ),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("password", sa.String(), nullable=True),
        sa.Column("last_login", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "id",
            sqlalchemy_utils.types.uuid.UUIDType(),
            server_default=sa.text(
                "(lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))),2) || '-' || substr('89ab',abs(random()) % 4 + 1, 1) || substr(lower(hex(randomblob(2))),2) || '-' || lower(hex(randomblob(6))))"
            ),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_users_name"), ["name"], unique=False
        )

    op.create_table(
        "game",
        sa.Column("date_planned", sa.DateTime(), nullable=True),
        sa.Column("date_started", sa.DateTime(), nullable=True),
        sa.Column("date_ended", sa.DateTime(), nullable=True),
        sa.Column(
            "course_id", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False
        ),
        sa.Column("player_count", sa.Integer(), nullable=True),
        sa.Column(
            "id",
            sqlalchemy_utils.types.uuid.UUIDType(),
            server_default=sa.text(
                "(lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))),2) || '-' || substr('89ab',abs(random()) % 4 + 1, 1) || substr(lower(hex(randomblob(2))),2) || '-' || lower(hex(randomblob(6))))"
            ),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["course_id"], ["course.id"], ondelete="cascade"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("game", schema=None) as batch_op:
        batch_op.create_index(
            "ix_game_date",
            ["date_started", "date_ended"],
            unique=False,
            postgresql_using="brin",
        )
        batch_op.create_index(
            "ix_game_date_planned",
            ["date_planned"],
            unique=False,
            postgresql_using="brin",
        )

    op.create_geospatial_table(
        "hole",
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column(
            "course_id", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False
        ),
        sa.Column(
            "area",
            Geometry(
                geometry_type="MULTIPOLYGON",
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
            ),
            nullable=True,
        ),
        sa.Column(
            "bunker",
            Geometry(
                geometry_type="MULTIPOLYGON",
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
            ),
            nullable=True,
        ),
        sa.Column(
            "fairway",
            Geometry(
                geometry_type="MULTIPOLYGON",
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
            ),
            nullable=True,
        ),
        sa.Column(
            "green",
            Geometry(
                geometry_type="POLYGON",
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
            ),
            nullable=True,
        ),
        sa.Column(
            "hole",
            Geometry(
                geometry_type="POINTZ",
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
            ),
            nullable=True,
        ),
        sa.Column(
            "water",
            Geometry(
                geometry_type="MULTIPOLYGON",
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
            ),
            nullable=True,
        ),
        sa.Column(
            "id",
            sqlalchemy_utils.types.uuid.UUIDType(),
            server_default=sa.text(
                "(lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))),2) || '-' || substr('89ab',abs(random()) % 4 + 1, 1) || substr(lower(hex(randomblob(2))),2) || '-' || lower(hex(randomblob(6))))"
            ),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["course_id"], ["course.id"], ondelete="cascade"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "course_id", "number", name="uniq_course_hole_number"
        ),
    )
    with op.batch_alter_table("hole", schema=None) as batch_op:
        batch_op.create_geospatial_index(
            "idx_hole_area",
            ["area"],
            unique=False,
            postgresql_using="gist",
            postgresql_ops={},
        )
        batch_op.create_geospatial_index(
            "idx_hole_bunker",
            ["bunker"],
            unique=False,
            postgresql_using="gist",
            postgresql_ops={},
        )
        batch_op.create_geospatial_index(
            "idx_hole_fairway",
            ["fairway"],
            unique=False,
            postgresql_using="gist",
            postgresql_ops={},
        )
        batch_op.create_geospatial_index(
            "idx_hole_green",
            ["green"],
            unique=False,
            postgresql_using="gist",
            postgresql_ops={},
        )
        batch_op.create_geospatial_index(
            "idx_hole_hole",
            ["hole"],
            unique=False,
            postgresql_using="gist",
            postgresql_ops={},
        )
        batch_op.create_geospatial_index(
            "idx_hole_water",
            ["water"],
            unique=False,
            postgresql_using="gist",
            postgresql_ops={},
        )

    op.create_table(
        "player",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column(
            "user_id", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False
        ),
        sa.Column(
            "id",
            sqlalchemy_utils.types.uuid.UUIDType(),
            server_default=sa.text(
                "(lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))),2) || '-' || substr('89ab',abs(random()) % 4 + 1, 1) || substr(lower(hex(randomblob(2))),2) || '-' || lower(hex(randomblob(6))))"
            ),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="cascade"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("player", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_player_name"), ["name"], unique=False
        )

    op.create_table(
        "game_player",
        sa.Column(
            "game_id", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False
        ),
        sa.Column(
            "player_id", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False
        ),
        sa.ForeignKeyConstraint(["game_id"], ["game.id"], ondelete="cascade"),
        sa.ForeignKeyConstraint(
            ["player_id"], ["player.id"], ondelete="cascade"
        ),
    )
    op.create_geospatial_table(
        "hole_tee",
        sa.Column(
            "point",
            Geometry(
                geometry_type="POINTZ",
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
            ),
            nullable=True,
        ),
        sa.Column(
            "hole_id", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False
        ),
        sa.Column(
            "id",
            sqlalchemy_utils.types.uuid.UUIDType(),
            server_default=sa.text(
                "(lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))),2) || '-' || substr('89ab',abs(random()) % 4 + 1, 1) || substr(lower(hex(randomblob(2))),2) || '-' || lower(hex(randomblob(6))))"
            ),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["hole_id"], ["hole.id"], ondelete="cascade"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("hole_tee", schema=None) as batch_op:
        batch_op.create_geospatial_index(
            "idx_hole_tee_point",
            ["point"],
            unique=False,
            postgresql_using="gist",
            postgresql_ops={},
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("hole_tee", schema=None) as batch_op:
        batch_op.drop_geospatial_index(
            "idx_hole_tee_point", postgresql_using="gist", column_name="point"
        )

    op.drop_geospatial_table("hole_tee")
    op.drop_table("game_player")
    with op.batch_alter_table("player", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_player_name"))

    op.drop_table("player")
    with op.batch_alter_table("hole", schema=None) as batch_op:
        batch_op.drop_geospatial_index(
            "idx_hole_water", postgresql_using="gist", column_name="water"
        )
        batch_op.drop_geospatial_index(
            "idx_hole_hole", postgresql_using="gist", column_name="hole"
        )
        batch_op.drop_geospatial_index(
            "idx_hole_green", postgresql_using="gist", column_name="green"
        )
        batch_op.drop_geospatial_index(
            "idx_hole_fairway", postgresql_using="gist", column_name="fairway"
        )
        batch_op.drop_geospatial_index(
            "idx_hole_bunker", postgresql_using="gist", column_name="bunker"
        )
        batch_op.drop_geospatial_index(
            "idx_hole_area", postgresql_using="gist", column_name="area"
        )

    op.drop_geospatial_table("hole")
    with op.batch_alter_table("game", schema=None) as batch_op:
        batch_op.drop_index("ix_game_date_planned", postgresql_using="brin")
        batch_op.drop_index("ix_game_date", postgresql_using="brin")

    op.drop_table("game")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_name"))

    op.drop_table("users")
    op.drop_table("course")
    # ### end Alembic commands ###
