"""empty message

Revision ID: eeb6c86597af
Revises: b4682cdc3418
Create Date: 2023-09-30 17:49:53.691771

"""
from alembic import op
from sqlalchemy.sql.schema import ScalarElementColumnDefault
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = "eeb6c86597af"
down_revision = "b4682cdc3418"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("course_hole", schema=None) as batch_op:
        batch_op.add_column(sa.Column("name", sa.String(), nullable=True))
        batch_op.add_column(
            sa.Column(
                "pos",
                sqlalchemy_utils.types.pg_composite.CompositeType(
                    "coordinates",
                    (
                        sa.Column("lat", sa.Float()),
                        sa.Column("lon", sa.Float()),
                        sa.Column(
                            "hgt", sa.Float(), default=ScalarElementColumnDefault(0.0)
                        ),
                    ),
                ),
                nullable=True,
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("course_hole", schema=None) as batch_op:
        batch_op.drop_column("pos")
        batch_op.drop_column("name")

    # ### end Alembic commands ###
